app1/urls.py
from django.urls import path
from app1.views import *

app_name = 'app1'

urlpatterns = [
    path('home/',home,name='home'),
]

app2/urls.py
from django.urls import path
from app2.views import *

app_name = 'app2'

urlpatterns = [
    path('seats/',seats,name='seats'),
]

project10/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2
from app3.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
    path('payment/',payment,name='payment')

]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app3/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request,'home.html')
    

app2/views.py
from django.shortcuts import render

# Create your views here.

def seats(request):
    return render(request,'seats.html')

app3/views.py
from django.shortcuts import render

# Create your views here.

def payment(request):
    return render(request,'payment.html')

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <h1 style="font-size: 40px;">Select the movie</h1>
    
    <a href="#" style="text-decoration: none;">
        <ol style="color: brown;">
        <li>Mission impossible</li>
        <li>Flash</li>
        <li>Bro</li>
        <li>oppenheimer</li>
        </ol>
    </a>

    <a href="{% url 'app2:seats' %}">Click here to go to Seat selection</a>
</body>
</html>

templates/payment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payment</title>
</head>
<body>
    <h1 style="font-size: 40px;">Make Your Payment Here</h1>
    <a href="#" style="text-decoration: none;">
        <ol style="color: blue; font-size:20px;">
        <li>Phonepe</li>
        <li>Gpay</li>
        <li>Paytm</li>
        <li>Amazon pay</li>
        </ol>
    </a>

    <a href="{% url 'app1:home' %}">Click here to go back to home page</a>
</body>
</html>

templates/seats.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Seats</title>
</head>
<body>
    <h1 style="font-size: 40px;">Please select your seats</h1>
    <h2 style="font-size: 3opx;">select your seats and make payment to confirm your Tickets</h2>

    <a href="{% url 'payment' %}">Click here to make payment</a>
   
</body>
</html>